---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  BreakMode
---
---@link  https://www.immomo.comBreakMode.html
---@enum BreakMode @parent class
BreakMode = {
	---
	---  BreakMode
	---
	CLIPPING = "value",

	---
	---  BreakMode
	---
	TAIL = "value",

	---
	---  BreakMode
	---
	HEAD = "value",

	---
	---  BreakMode
	---
	MIDDLE = "value"

}