---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  缓存策略
---
---@link  https://www.immomo.comCachePolicy.html
---@enum CachePolicy @parent class
CachePolicy = {
	---
	---  缓存策略
	---
	CACHE_ONLY = "value",

	---
	---  缓存策略
	---
	REFRESH_CACHE_BY_API = "value",

	---
	---  缓存策略
	---
	API_ONLY = "value",

	---
	---  缓存策略
	---
	CACHE_THEN_API = "value",

	---
	---  缓存策略
	---
	CACHE_OR_API = "value"

}