---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  自定义View弹窗
---
---@class Dialog : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "Dialog"}

---
---  构造方法
---
---@return Dialog 
function Dialog()
	return _class
end

---
---  设置点击蒙版是否可取消
---
---@param cancelable boolean  点击蒙版是否可取消
---@return Dialog 
---@note  默认可点击可消失
function _class:cancelable(cancelable)
	return self
end

---
---  获取点击蒙版是否可取消状态
---
---@return boolean 布尔值
function _class:cancelable()
	return true
end

---
---  显示弹窗
---
---@return Dialog 
function _class:show()
	return self
end

---
---  取消弹窗显示
---
---@return Dialog 
function _class:dismiss()
	return self
end

---
---  dialog消失回调
---
---@param disAppearCallback fun():void
---	 回调格式：
---		 ``` 
---		 function() 
---		 end
---		```
---@return Dialog 
function _class:dialogDisAppear(disAppearCallback)
	return self
end

---
---  设置内容View
---
---@param content View  自定义内容view
---@return Dialog 
function _class:setContent(content)
	return self
end

---
---  设置背景黑色阴影alpha值
---
---@param alpha number  alpha值，范围0~1
---@return Dialog 
function _class:setDimAmount(alpha)
	return self
end

return _class