---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  图片展示类控件，目前两端支持自适应尺寸，前提是一边固定，SDK根据图片比例自行计算另一边的尺寸
---
---
---  用于本地或者网络图片展示，可以添加点击事件
---
---@note  非容器视图，不可以添加子视图
---@class ImageView : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "ImageView"}

---
---  创建图片展示控件实例
---
---@return ImageView 
function ImageView()
	return _class
end

---
---  设置图片的填充模式
---
---@param contentMode ContentMode  填充模式的枚举值
---@return ImageView 
---@note  默认为SCALE_ASPECT_FIT，详情参见[ContentMode](ContentMode)；模式要在设置图片前设置，不建议动态修改
function _class:contentMode(contentMode)
	return self
end

---
---  获取图片填充模式
---
---@return number 图片填充模式枚举值
---@note  默认为SCALE_ASPECT_FIT，详情参见[ContentMode](ContentMode)
function _class:contentMode()
	return 0
end

---
---  设置在滚动控件中，滚动时是否加载图片，默认为true不加载
---
---@param lazyLoad boolean  true滑动时不加载图片，false滑动时候加载
---@return ImageView 
---@note  该属性为Android端特性，iOS设置时无效果
function _class:lazyLoad(lazyLoad)
	return self
end

---
---  获取在滚动控件中，滚动时是否加载图片，默认为true不加载
---
---@return boolean true滑动时不加载图片，false滑动时候加载
---@note  该属性为Android端特性，iOS设置时无效果
function _class:lazyLoad()
	return true
end

---
---  开始播放图片的帧动画，支持本地及网络图片
---
---@param images table  图片的集合
---@param during number  播放时长
---@param repeat boolean  是否重复，默认不重复
---@return ImageView 
function _class:startAnimationImages(images, during, repeat)
	return self
end

---
---  停止播放图片的帧动画
---
---@return ImageView 
function _class:stopAnimationImages()
	return self
end

---
---  是否正在播放图片帧动画
---
---@return boolean 
function _class:isAnimating()
	return true
end

---
---  可以设置网络或本地图片
---
---@param url string  网络URL、本地图片名称或本地path
---@return ImageView 
function _class:image(url)
	return self
end

---
---  设置图片及占位图
---
---@param image string  本地图片path或网络图片URL
---@param holder string  占位图path或者URL
---@return ImageView 
function _class:setImageUrl(image, holder)
	return self
end

---
---  设置图片及占位图，并且切割圆角
---
---
---  该方法会在第一次加载图片时异步将图片裁剪出相应圆角，之后再次加载不在需要额外处理。
---
---@param image string  本地图片path或网络图片URL
---@param holder string  占位图path或者URL
---@param corner number  圆角大小
---@param direct RectCorner  圆角位置枚举，详情见[RectCorner](RectCorner)
---@return ImageView 
---@note  用于改善图片圆角切割带来的性能问题，多图片圆角推荐使用
function _class:setCornerImage(image, holder, corner, direct)
	return self
end

---
---  设置图片、占位图及回调
---
---@param image string  本地图片path或网络图片URL
---@param holder string  占位图path或者URL
---@param callback fun(success:boolean, error:string, imgURL:string):void
---	 图片加载结果回调，格式为：
---		```
---		function(success, error, imgURL)
---			--- success为boolean，加载是否成功
---			--- error为string，加载失败的信息
---			--- imgURL为string，请求的图片地址
---		end
---		```
---		
---@return ImageView 
function _class:setImageWithCallback(image, holder, callback)
	return self
end

---
---  加载.9图
---
---@param image string  本地图片地址
---@return ImageView 
---@note  Android为drawable目录下相对路径，无后缀，iOS需要使用带.9名称后缀图片
function _class:setNineImage(image)
	return self
end

---
---  设置ImageView高斯模糊效果
---
---@param number number  高斯模糊程度 0 ~ 25，数值越大，模糊越明显
---@param bool boolean  true：采用处理图片高斯模糊方式(PS:性能较差效果较好)，false：图片上覆盖一个白色蒙层 (android都按高斯模糊处理）
---@return ImageView 
---@note  iOS下为全ImageView模糊，提高效率，故需要ImageView设置填充模式
function _class:blurImage(number, bool)
	return self
end

return _class