---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  图片按钮控件
---
---@note  图片按钮控件只能设置图片，不能设置文字,如果不考虑按压时候的状态，请使用[ImageView](ImageView)，
---		非容器视图，不可以添加子视图
---@class ImageButton : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "ImageButton"}

---
---  创建图片按钮实例
---
---@return ImageButton 
function ImageButton()
	return _class
end

---
---  为控件设置图片，支持本地及网络图片
---
---@param url string  在正常情况下显示图片的path或URL
---@param url string  在press情况下显示图片的path或URL
---@return ImageButton 
function _class:setImage(url, url)
	return self
end

return _class