---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  动画插值器类型
---
---@link  https://www.immomo.comInterpolatorType.html
---@enum InterpolatorType @parent class
InterpolatorType = {
	---
	---  动画插值器类型
	---
	Accelerate = "value",

	---
	---  动画插值器类型
	---
	Decelerate = "value",

	---
	---  动画插值器类型
	---
	Overshoot = "value",

	---
	---  动画插值器类型
	---
	Linear = "value",

	---
	---  动画插值器类型
	---
	AccelerateDecelerate = "value",

	---
	---  动画插值器类型
	---
	Bounce = "value"

}