---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  支持横竖向排布的容器视图控件
---
---
---  线性容器，类似Android原生LinearLayout的一种容器视图。分为横向和竖向，根据插入View的顺序依次布局。宽高可自适应。
---
---@note  该视图目前只支持单行
---@class LinearLayout : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "LinearLayout"}

---
---  创建线性容器控件,默认为横向
---
---@param direct LinearType  布局方向枚举
---@return LinearLayout 
---@note  布局方向参见[LinearType](LinearType)
function LinearLayout(direct)
	return _class
end

---
---  立即请求布局
---
---
---  通常情况下布局是Android会在下一帧渲染前自动布局，iOS会在当前runloop结束前自动布局，
---		谨慎使用该方法，除非你知道自己必须使用它来完成一些特殊操作
---
---@return LinearLayout 
---@note  请谨慎使用该方法
function _class:requestLayout()
	return self
end

return _class