---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  开关视图控件
---
---@note  非容器视图，不可以添加子视图
---@class Switch : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "Switch"}

---
---  创建开关视图
---
---@return Switch 
function Switch()
	return _class
end

---
---  设置开关状态
---
---@param isOn boolean 
---@return Switch 
---@note  两端默认小球颜色和选中主题色可能不一致，如需保持一致，建议使用setThumbColor和setSelectedColor方法自定义设置
function _class:on(isOn)
	return self
end

---
---  获取开关状态
---
---@return boolean 
function _class:on()
	return true
end

---
---  开关状态改变回调
---
---@param callback fun(isOn:boolean):void
---	 样式为：
---		```
---		function(isOn)
---			--- isOn boolean类型
---		end
---		```
---		
---@return Switch 
function _class:setSwitchChangedCallback(callback)
	return self
end

---
---  设置圆点颜色
---
---@param thumbColor Color  颜色
---@return Switch 
function _class:setThumbColor(thumbColor)
	return self
end

---
---  设置边框以及背景色，未选中主题色
---
---@param normalColor Color  颜色
---@return Switch 
---@note  Android系统在6.0以上该方法才生效
function _class:setNormalColor(normalColor)
	return self
end

---
---  设置选中后的主题色
---
---@param selectedColor Color  颜色
---@return Switch 
---@note  Android系统在6.0以上该方法才生效
function _class:setSelectedColor(selectedColor)
	return self
end

return _class