---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  标签切换控件
---
---@class TabSegmentView : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "TabSegmentView"}

---
---  构造方法
---
---
---  构造方法，根据frame，标题数组，字体颜色，初始化一个控件实例
---
---@param frame Rect  frame：需要设置的位置和宽高
---@param titles Array  titles：字符串数组
---@param tintColor Color  tintColor：字体颜色
---@return TabSegmentView 
function TabSegmentView(frame, titles, tintColor)
	return _class
end

---
---  设置当前的页数
---
---@param cIndex number  页码值
---@return TabSegmentView 
function _class:currentIndex(cIndex)
	return self
end

---
---  获取当前的选中页
---
---@return number 
function _class:currentIndex()
	return 0
end

---
---  设置默认字体大小
---
---@param fontSize number  字体大小
---@return TabSegmentView 
function _class:normalFontSize(fontSize)
	return self
end

---
---  获取默认字体大小
---
---@return number 字体大小
function _class:normalFontSize()
	return 0
end

---
---  设置选中时放大比例
---
---@param scale number  比例值，默认1.6
---@return TabSegmentView 
---@note  在有必要修改时，尽量在创建完就进行设置
function _class:selectScale(scale)
	return self
end

---
---  获取选中时的放大比例
---
---
---  获取选中时的放大比例
---
---@return number 
function _class:selectScale()
	return 0
end

---
---  设置字体颜色
---
---@param tintColor Color  需要设置的字体颜色
---@return TabSegmentView 
---@note  该控件不支持颜色渐变
function _class:tintColor(tintColor)
	return self
end

---
---  获取当前设置的字体颜色
---
---@return Color 字体颜色值
function _class:tintColor()
	return Color()
end

---
---  设置选中tab字体颜色
---
---@param selectedColor Color  需要设置的字体颜色
---@return TabSegmentView 
function _class:selectedColor(selectedColor)
	return self
end

---
---  与ViewPager绑定，实现联动效果
---
---
---  通过事件绑定，创造出良好的联动效果，建议在两个控件都初始化完毕后再进行绑定操作
---
---@param viewPager ViewPager  需要绑定的ViewPager实例对象
---@param animated boolean  animated:切换是否触发动画
---@return TabSegmentView 
---@note  当前选中的索引数会同步给ViewPager
function _class:relatedToViewPager(viewPager, animated)
	return self
end

---
---  切换选中的标签索引
---
---@param index number  index：想要选中的页数
---@param animated boolean  animated：是否动画切换
---@return TabSegmentView 
---@note  默认无动画
function _class:setCurrentIndexAnimated(index, animated)
	return self
end

---
---  修改某个标签索引的标题
---
---@param title string  title：标题
---@param index number  index：索引,从1开始
---@return TabSegmentView 
function _class:setTapTitleAtIndex(title, index)
	return self
end

---
---  设置某个标签的标注数
---
---@param count number  count：标注数，传0隐藏
---@param index number  index：标签索引
---@return TabSegmentView 
function _class:setTapBadgeNumAtIndex(count, index)
	return self
end

---
---  设置标注文本
---
---@param badgeTitle string  标签的标注文本，标题上方的提示性内容
---@param index number  标签索引
---@return TabSegmentView 
function _class:setTapBadgeTitleAtIndex(badgeTitle, index)
	return self
end

---
---  改变红点状态
---
---@param index number  标签索引
---@param isShow boolean  是否展示（默认隐藏）
---@return TabSegmentView 
---@note  该方法命名有歧义，目前已废弃，如有需求，请使用changeRedDotStatusAtIndex方法，参数一致
function _class:setRedDotHiddenAtIndex(index, isShow)
	return self
end

---
---  改变红点状态
---
---@param index number  index:标签索引
---@param isShow boolean  isShow:是否展示（默认隐藏）
---@return TabSegmentView 
function _class:changeRedDotStatusAtIndex(index, isShow)
	return self
end

---
---  设置标签切换后的回调
---
---@param callback fun(index:number):void
---	 回调格式：
---		 ``` 
---		 function(number index) 
---		 	 ---index:被选中的标签索引 
---		 end
---		```
---@return TabSegmentView 
---@note  点击当前的不回调
function _class:setTabSelectedListener(callback)
	return self
end

---
---  设置标签点击的回调
---
---@param callback fun(index:number):void
---	 回调格式：
---		 ``` 
---		 function(number index) 
---		 	 ---index:被点击的标签索引 
---		 end
---		```
---@return TabSegmentView 
---@note  该回调会在每一次点击后触发
function _class:setItemTabClickListener(callback)
	return self
end

---
---  设置控件的布局样式，默认居左
---
---
---  当业务方在标签数较少的情况下需要将所有标签居中展示时，可以使用该方法进行设置
---
---@param alignment TabSegmentAlignment  LEFT:居左,CENTER:居中,RIGHT:居右,默认居左
---@return TabSegmentView 
---@note  该属性仅在标签占位小于总宽度的时候有效，而且居左布局基本无意义
function _class:setAlignment(alignment)
	return self
end

---
---  设置标签之间的间距，单位dp
---
---
---  当业务放有需求放大或缩小文本之间的间距时，使用该方法进行设置
---
---@param spacing number  间距值
---@return TabSegmentView 
function _class:setTabSpacing(spacing)
	return self
end

---
---  设置indicator 颜色
---
---@param indicatorColor Color  颜色
---@return TabSegmentView 
function _class:indicatorColor(indicatorColor)
	return self
end

return _class