---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  StyleString下划线样式
---
---
---  StyleString下划线样式
---
---@link  https://www.immomo.comUnderlineStyle.html
---@enum UnderlineStyle @parent class
UnderlineStyle = {
	---
	---  StyleString下划线样式
	---
	---
	---  StyleString下划线样式
	---
	LINE = "value",

	---
	---  StyleString下划线样式
	---
	---
	---  StyleString下划线样式
	---
	NONE = "value"

}