---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  一个可自动滚动可翻页的控件
---
---
---  该控件提供了无限滚动，自动滚动，手动切换页面等功能，更可以同TabSegment控件进行联动，开发出复杂的联动效果
---
---@class ViewPager : View @parent class
---@field name string 
local _class = {
	_priveta_class_name = "ViewPager"}

---
---  构造方法
---
---
---  构造方法，生成实例对象
---
---@return ViewPager 
function ViewPager()
	return _class
end

---
---  设置数据和事件的适配器
---
---
---  在创建完适配器后，通过该方法绑定到ViewPager控件上
---
---@param adapter ViewPagerAdapter  负责页面初始化以及事件回传
---@return ViewPager 
---@note  鉴于设置adapter时会触发刷新，尽量初始化完毕后再进行设置
function _class:adapter(adapter)
	return self
end

---
---  获取当前控件所绑定的适配器
---
---
---  获取已经绑定的adapter对象
---
---@return ViewPagerAdapter 返回一个ViewPagerAdapter实例对象
function _class:adapter()
	return ViewPagerAdapter()
end

---
---  控制是否开启自动滚动
---
---
---  控制是否开启自动滚动,开启后ViewPager会自动滚动。未开启无限滚动时，ViewPager滚动到最后一页后会返回第一页重新开始。开启无限滚动后，ViewPager页面会自动无限滚动
---
---@param enable boolean  是否开启自动滚动
---@return ViewPager 
function _class:autoScroll(enable)
	return self
end

---
---  获取当前设置的自动滚动状态
---
---@return boolean 返回布尔值
function _class:autoScroll()
	return true
end

---
---  设置是否循环滚动，默认为false
---
---
---  设置是否开启循环滚动，开启后同方向可以无限循环滚动。当绑定TabSegmentView控件后，不能无限循环滚动
---
---@param enable boolean  是否开启循环滚动
---@return ViewPager 
---@note  绑定了[TabSegmentView](TabSegmentView)后不可用。状态修改后，一定要reloadData
function _class:recurrence(enable)
	return self
end

---
---  获取当前循环滚动状态
---
---@return boolean 
function _class:recurrence()
	return true
end

---
---  设置自动滚动的时间间隔，默认为2s
---
---@param time number  单位s
---@return ViewPager 
function _class:frameInterval(time)
	return self
end

---
---  获取自动滚动的时间间隔
---
---@return number 单位s
function _class:frameInterval()
	return 0
end

---
---  控制是否展示指示器
---
---
---  控制器滚动指示器的展示和隐藏，默认为true展示
---
---@param show boolean  是否展示指示器
---@return ViewPager 
function _class:showIndicator(show)
	return self
end

---
---  获取指示器的状态
---
---
---  获取当前指示器的展示状态，true为展示
---
---@return boolean 布尔值
function _class:showIndicator()
	return true
end

---
---  控制是否开启预加载
---
---
---  控制是否开启预加载，提前加载上一页和下一页
---
---@param open boolean  是否开启预加载
---@return ViewPager 
function _class:aheadLoad(open)
	return self
end

---
---  获取是否开启预加载
---
---
---  获取是否开始了预加载
---
---@return boolean 布尔值
function _class:aheadLoad()
	return true
end

---
---  page页结束滚动时回调
---
---
---  设置page页结束滚动时的回调，会回调结束滚动时的页面位置
---
---@param callback fun(position):void
---	 回调格式：
---		 ``` 
---		 function(number position) 
---		 	 ---position:结束滚动的page页在ViewPager的位置 
---		 end
---		```
---@return ViewPager 
---@note  索引从1开始
function _class:endDragging(callback)
	return self
end

---
---  滑动后选中具体页面位置回调
---
---@param callback fun(position:number):void
---	 回调格式：
---		 ``` 
---		 function(number position) 
---		 	 ---position:结束滚动的page页在ViewPager的位置 
---		 end
---		```
---@return ViewPager 
---@note  如果还是在当前Page页面，则不会回调，只有页面position发生变化后才会回调
function _class:onChangeSelected(callback)
	return self
end

---
---  刷新所有的数据
---
---
---  用来刷新当前控件的所有数据
---
---@return ViewPager 
function _class:reloadData()
	return self
end

---
---  滚动到某页
---
---
---  滚动到某页，可以控制是否在滚动过程中执行动画
---
---@param position number  页面坐标
---@param animated boolean  是否开启动画
---@return ViewPager 
function _class:scrollToPage(position, animated)
	return self
end

---
---  设置指示器当前帧的颜色
---
---
---  设置指示器当前帧的颜色
---
---@param color Color  颜色
---@return ViewPager 
function _class:currentPageColor(color)
	return self
end

---
---  设置指示器默认点的颜色
---
---
---  设置指示器默认点的颜色
---
---@param color Color  颜色
---@return ViewPager 
function _class:pageDotColor(color)
	return self
end

---
---  获取ViewPager当前页的页数
---
---@return number 页数
function _class:currentPage()
	return 0
end

---
---  设置预加载页面数量
---
---
---  设置预加载页面数量，Android专用，iOS空实现，默认为1：左右各预加载一页，0：不预加载
---
---@param count number  预加载的页数
---@return ViewPager 
---@note  Android专用
function _class:setPreRenderCount(count)
	return self
end

---
---  设置cell将要显示回调
---
---
---  设置cell将要显示的回调，业务可以在cell即将显示的时候做一些处理
---
---@param callback fun(cell:table, position:number):void
---	 回调格式：
---		 ``` 
---		 function(table cell,number position) 
---		 	 ---cell：将要展示的cell 
---		 	 ---position：将要展示的索引 
---		 end
---		```
---@return ViewPager 
function _class:cellWillAppear(callback)
	return self
end

---
---  设置cell已经消失的回调
---
---
---  设置cell已经消失的回调，业务可以在cell已经消失后做一些处理
---
---@param callback fun(cell:table, position:number):void
---	 回调格式：
---		 ``` 
---		 function(table cell, number position) 
---		 	 ---cell：将要消失的cell  
---		 	 ---position：将要消失的索引 
---		 end
---		```
---@return ViewPager 
function _class:cellDidDisappear(callback)
	return self
end

---
---  设置点击了某一页的回调
---
---
---  设置点击了某一页的回调，回调选中也的page索引值
---
---@param callback fun(position:number):void
---	 回调格式：
---		 ``` 
---		 function(number position) 
---		 	 ---page：点击的页码 
---		 end
---@return ViewPager 
function _class:setPageClickListener(callback)
	return self
end

---
---  设置是否开可滚动
---
---
---  设置是否开启滚动，默认为true
---
---@param enable boolean  是否开启滚动
---@return ViewPager 
function _class:setScrollEnable(enable)
	return self
end

---
---  设置滚动百分比回调
---
---@param callback fun(progress:number, fromIndex:number, toIndex:number):void
---	 回调格式：
---		 ``` 
---		 function(number progress, number fromIndex, number toIndex) 
---		 	 ---progress：滚动的百分比 
---		 	 ---fromIndex：滚动前page的索引 
---		 	 ---toIndex：滚动后page的索引 
---		 end
---		```
---@return ViewPager 
function _class:setTabScrollingListener(callback)
	return self
end

return _class