---
--- Generated by MLN Team (https://www.immomo.com)
--- Created by MLN Team.
--- DateTime: 15-01-2020 17:35
---

---
---  瀑布流,展示高度不一的数据流
---
---
---  瀑布流，主要用来展示比例不一致的数据，控件会根据回调的高度对每个元素逐个排布
---
---@note  该控件只有布局，具体想要产生效果需要配合布局和数据源方法的类一起, iOS默认展示滚动指示，android默认不展示
---@class WaterfallView : CollectionView @parent class
---@field name string 
local _class = {
	_priveta_class_name = "WaterfallView"}

---
---  构造方法
---
---
---  构造方法，创建实例对象，通过参数控制数据更新事件。
---
---@param refreshEnable boolean  是否开启下拉刷新
---@param loadEnable boolean  是否开启上拉加载
---@return WaterfallView 返回控件实例
function WaterfallView(refreshEnable, loadEnable)
	return _class
end

---
---  添加瀑布流布局的header
---
---
---  给瀑布流布局增加一个自定义的头部视图，业务方可以自由定义内容
---
---@param headerView View  自定义的header视图
---@return WaterfallView 
---@note  header需要业务设置好尺寸，添加后不会有任何约束处理，此方法已废弃，请使用WaterfallAdapter中[initHeader、fillHeaderData、headerValid等方法](WaterfallAdapter)
function _class:addHeaderView(headerView)
	return self
end

---
---  移除已经添加的header视图
---
---
---  在不需要展示header时，可以用该方法移除
---
---@return WaterfallView 
---@note  此方法已废弃，请使用WaterfallAdapter中[initHeader、fillHeaderData、headerValid等方法](WaterfallAdapter)
function _class:removeHeaderView()
	return self
end

---
---  设置数据加载指示器是否占用一行，默认不占用
---
---
---  设置数据加载指示器是否占用一行，默认不占用，Android有效
---
---@param isUse boolean  是否开启
---@return WaterfallView 
---@note  iOS无效
function _class:useAllSpanForLoading(isUse)
	return self
end

return _class